import { describe, expect, it } from 'vitest';
import type { ContentStatus } from '@taproot/core';

import { STATUS_META, STATUS_ORDER, parseStatusFilter, statusFilterOptions, statusMeta } from './status.js';

const noCounts: Record<ContentStatus, number> = {
  draft: 0,
  in_review: 0,
  scheduled: 0,
  published: 0,
  archived: 0,
};

describe('status metadata', () => {
  it('covers every status in the order list', () => {
    for (const status of STATUS_ORDER) {
      expect(STATUS_META[status]).toBeDefined();
    }
    expect(Object.keys(STATUS_META).sort()).toEqual([...STATUS_ORDER].sort());
  });

  it('writes badge classes out in full, because Tailwind scans source text', () => {
    // A class assembled at runtime is never generated by Tailwind and the badge renders unstyled.
    // Nothing here may contain a template placeholder.
    for (const status of STATUS_ORDER) {
      expect(STATUS_META[status].badgeClass).not.toContain('${');
      expect(STATUS_META[status].badgeClass).toMatch(/^border-status-\S+ bg-status-\S+-subtle$/);
    }
  });

  it('gives each status its own colour', () => {
    const classes = STATUS_ORDER.map((status) => STATUS_META[status].badgeClass);
    expect(new Set(classes).size).toBe(STATUS_ORDER.length);
  });

  it('falls back to a neutral badge for a status this build does not know', () => {
    const meta = statusMeta('pending_legal_review');

    expect(meta.label).toBe('pending legal review');
    expect(meta.badgeClass).toBe('border-border bg-surface-sunken');
    // Unknown means untrusted: it must not be offered in the editor. Whether a contributor may
    // move an item into it is `statusRequiresPublish`'s question, tested in guards.test.ts.
    expect(meta.settable).toBe(false);
  });
});

describe('parseStatusFilter', () => {
  it('accepts every known status', () => {
    for (const status of STATUS_ORDER) {
      expect(parseStatusFilter(status)).toBe(status);
    }
  });

  it('rejects empty and unknown values', () => {
    expect(parseStatusFilter(null)).toBeUndefined();
    expect(parseStatusFilter(undefined)).toBeUndefined();
    expect(parseStatusFilter('')).toBeUndefined();
    expect(parseStatusFilter('published; drop table')).toBeUndefined();
    expect(parseStatusFilter('Published')).toBeUndefined();
  });

  it('rejects inherited object keys', () => {
    // The reason membership is tested against the list rather than with `in`: `'toString' in
    // STATUS_META` is true, which would put a junk value into the query.
    expect(parseStatusFilter('toString')).toBeUndefined();
    expect(parseStatusFilter('constructor')).toBeUndefined();
    expect(parseStatusFilter('__proto__')).toBeUndefined();
  });
});

describe('statusFilterOptions', () => {
  it('always offers the statuses the editor can set, even at zero', () => {
    const offered = statusFilterOptions(noCounts, undefined).map((option) => option.status);

    expect(offered).toEqual(['draft', 'in_review', 'published', 'archived']);
  });

  it('adds a non-settable status once something is in it', () => {
    const offered = statusFilterOptions({ ...noCounts, scheduled: 2 }, undefined);

    expect(offered.find((option) => option.status === 'scheduled')?.count).toBe(2);
  });

  it('keeps the selected status even when nothing matches it', () => {
    // Dropping it would silently reset the filter the page is currently applying, so the list
    // would show everything while the select claimed to be narrowing it.
    const offered = statusFilterOptions(noCounts, 'scheduled').map((option) => option.status);

    expect(offered).toContain('scheduled');
  });

  it('preserves workflow order rather than count order', () => {
    const offered = statusFilterOptions(
      { draft: 1, in_review: 9, scheduled: 4, published: 2, archived: 3 },
      undefined,
    ).map((option) => option.status);

    expect(offered).toEqual(STATUS_ORDER);
  });
});
