// Generated by Taproot. Do not edit by hand.
//
// Run `npm run taproot:types` to regenerate after changing the content model. This file is
// checked in on purpose: a schema change should show up as a reviewable diff, and the moment
// a field is renamed the templates that used it stop compiling.
//
// Source: http://localhost:4321/api/taproot/delivery/schema
/** An id referring to a media asset. Look it up in a delivery response’s `media` map. */
export type MediaId = string;
/** An id referring to another content item. Look it up in `references`. */
export type ContentItemId = string;
/** An id referring to a taxonomy term. Look it up in `terms`. */
export type TermId = string;
/** Hero — `hero` (block). */
export interface HeroData {
  heading: string;
  /** One or two sentences under the heading. */
  lead?: string;
  image?: MediaId;
}
/** Call to action — `call_to_action` (block). */
export interface CallToActionData {
  text: string;
  link_label: string;
  /** A path on this site, or a full address. */
  link_href: string;
}
/** Rich text — `prose` (block). */
export interface ProseData {
  body: string;
}
/** Quote — `quote` (block). */
export interface QuoteData {
  quote: string;
  attribution?: string;
}
/** Gallery — `gallery` (block). */
export interface GalleryData {
  /** They appear in the order listed. Use the move buttons to change it. */
  images: MediaId[];
  caption?: string;
}
/** Any block instance, discriminated by `type`. */
export type TaprootBlock =
  | ({ id: string; type: "hero"; reusable?: false } & HeroData)
  | { id: string; type: "hero"; reusable: true; ref: string; data: HeroData }
  | ({ id: string; type: "call_to_action"; reusable?: false } & CallToActionData)
  | { id: string; type: "call_to_action"; reusable: true; ref: string; data: CallToActionData }
  | ({ id: string; type: "prose"; reusable?: false } & ProseData)
  | { id: string; type: "prose"; reusable: true; ref: string; data: ProseData }
  | ({ id: string; type: "quote"; reusable?: false } & QuoteData)
  | { id: string; type: "quote"; reusable: true; ref: string; data: QuoteData }
  | ({ id: string; type: "gallery"; reusable?: false } & GalleryData)
  | { id: string; type: "gallery"; reusable: true; ref: string; data: GalleryData }
/** Page — `page` (page). */
export interface PageData {
  /** One or two sentences shown in listings and search results. */
  summary?: string;
  body?: string;
  show_in_nav?: boolean;
  /** Which parts of the college this page relates to. */
  departments?: TermId[];
  /** Composed blocks rendered under the body. */
  sections?: TaprootBlock[];
}
/** Event — `event` (collection). */
export interface EventData {
  starts_at: string;
  location?: string;
  /** Who the event is aimed at. */
  audience?: "prospective" | "current" | "staff" | "alumni";
  body?: string;
  /** Maximum attendees. Leave blank for unlimited. */
  capacity?: number;
  /** Sessions within the event, in the order they run. */
  schedule?: {
    time: string;
    what: string;
    room?: string;
  }[];
  /** The department or programme page this event belongs to. */
  host_page?: ContentItemId;
}
/** Weather Banner — `weather_banner` (singleton). */
export interface WeatherBannerData {
  enabled?: boolean;
  message?: string;
  severity?: "info" | "warning" | "closure";
}
/** Every content type, keyed by `api_id`. */
export interface TaprootContentTypes {
  page: PageData;
  event: EventData;
  weather_banner: WeatherBannerData;
}
export type TaprootContentTypeId = keyof TaprootContentTypes;
