// Generated by Taproot. Do not edit by hand.
//
// Run `npm run taproot:types` to regenerate after changing the content model. This file is
// checked in on purpose: a schema change should show up as a reviewable diff, and the moment
// a field is renamed the templates that used it stop compiling.
//
// Source: http://localhost:4321/api/taproot/delivery/schema
/** An id referring to a media asset. Look it up in a delivery response’s `media` map. */
export type MediaId = string;
/** An id referring to another content item. Look it up in `references`. */
export type ContentItemId = string;
/** An id referring to a taxonomy term. Look it up in `terms`. */
export type TermId = string;
/** A saved query. Its results are in a delivery response’s `queries` map, not here. */
export interface TaprootQuery {
  termIds: TermId[];
  sort: "path" | "title" | "newest" | "oldest" | "recently_updated" | "field_asc" | "field_desc";
  limit: number;
}
/** Hero — `hero` (block). */
export interface HeroData {
  heading: string;
  /** One or two sentences under the heading. */
  lead?: string;
  image?: MediaId;
}
/** Call to action — `call_to_action` (block). */
export interface CallToActionData {
  text: string;
  link_label: string;
  /** A path on this site, or a full address. */
  link_href: string;
}
/** Rich text — `prose` (block). */
export interface ProseData {
  body: string;
}
/** Quote — `quote` (block). */
export interface QuoteData {
  quote: string;
  attribution?: string;
}
/** Gallery — `gallery` (block). */
export interface GalleryData {
  /** They appear in the order listed. Use the move buttons to change it. */
  images: MediaId[];
  caption?: string;
}
/** Event listing — `event_listing` (block). */
export interface EventListingData {
  heading?: string;
  /** Published events matching this appear automatically — nobody edits this page. */
  events?: TaprootQuery;
}
/** Any block instance, discriminated by `type`. */
export type TaprootBlock =
  | { id: string; type: "hero"; data: HeroData; ref?: string }
  | { id: string; type: "call_to_action"; data: CallToActionData; ref?: string }
  | { id: string; type: "prose"; data: ProseData; ref?: string }
  | { id: string; type: "quote"; data: QuoteData; ref?: string }
  | { id: string; type: "gallery"; data: GalleryData; ref?: string }
  | { id: string; type: "event_listing"; data: EventListingData; ref?: string }
/** Page — `page` (page). */
export interface PageData {
  /** One or two sentences shown in listings and search results. */
  summary?: string;
  body?: string;
  show_in_nav?: boolean;
  /** Which parts of the college this page relates to. */
  departments?: TermId[];
  /** Composed blocks rendered under the body. */
  sections?: TaprootBlock[];
}
/** Event — `event` (collection). */
export interface EventData {
  starts_at: string;
  location?: string;
  /** Who the event is aimed at. */
  audience?: "prospective" | "current" | "staff" | "alumni";
  body?: string;
  /** Maximum attendees. Leave blank for unlimited. */
  capacity?: number;
  /** Sessions within the event, in the order they run. */
  schedule?: {
    id: string;
    data: {
      time: string;
      what: string;
      room?: string;
    };
  }[];
  /** The department or programme page this event belongs to. */
  host_page?: ContentItemId;
  /** Where people sign up — a page here, a file, or an external booking system. */
  registration_link?: ({ kind: "item"; id: ContentItemId; label?: string; newTab: boolean; noFollow: boolean } | { kind: "media"; id: MediaId; label?: string; newTab: boolean; noFollow: boolean } | { kind: "url"; href: string; label?: string; newTab: boolean; noFollow: boolean });
}
/** Weather Banner — `weather_banner` (singleton). */
export interface WeatherBannerData {
  enabled?: boolean;
  message?: string;
  severity?: "info" | "warning" | "closure";
}
/** Person — `person` (collection). */
export interface PersonData {
  /** Job title, as it should appear under their name. */
  position?: string;
  photo?: MediaId;
  /** One or more. Somebody can sit in two. */
  department?: TermId[];
  email?: string;
  phone?: string;
}
/** Every content type, keyed by `api_id`. */
export interface TaprootContentTypes {
  page: PageData;
  event: EventData;
  weather_banner: WeatherBannerData;
  person: PersonData;
}
export type TaprootContentTypeId = keyof TaprootContentTypes;
